### ISSUE TITLE
Introduce shared components libarires into aries bifold

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/bifold-wallet#617]
With the demo-wallet using the latest version of AFJ `core` and `react-native`, we can start introducing the shared components.

## Todo

- [ ] Swap the `indy-sdk` package for the shared components
- [ ] Verify react-hooks still works.
- [ ] Manually go through the animo demo and verify all flows work
    - [ ] Creating connections
    - [ ] Receiving credentials
    - [ ] Presenting proofs
- [ ] Once indy sdk has been removed, test in a simulator environment
  
> **Open questions**
>     - Do we want to keep two branches for now? One that uses `indy-sdk` and one that uses shared components?
>     - 

For now we keep both indy-sdk and shared components. Once all shared components have been integrated and indy-sdk has been removed from core we can remove indy-sdk
